### ISSUE TITLE
Unable to query endpoint in docker network

### ISSUE THREAD

**Issue by JMartinCollins** [wp-graphql/wp-graphql#2018]
Calling node-fetch to the GraphQL endpoint server side fails inside Docker Container Networks.

The problem and a good explanation are shown here: [(https://stackoverflow.com/a/68298683)]

There are workarounds that can make it work, but the problem is that the fetch in the Docker network is going to http://network-alias-here/graphql, which probably gets resolved to the container's subnet IP, and for some reason wordpress/wpgraphql needs the request URI to match(i.e. no aliases or IP addresses).

If anyone has interesting solutions to get this working smoothly I'm all ears. I've found one solution involves running the node app service directly from npm cli, where it's outside docker's host.docker.internal hostname(which just is in hosts as a 192.168.. IP btw)

**Comment by chriszarate** [comment]
You need your installed WordPress URL to match your Docker network alias. The easiest way, in my opinion, is to add the service name of your WordPress container (which Docker uses as the default network alias) to your computer's `/etc/hosts` file against `127.0.0.1`. Take note that the ports must also match, so your Docker Compose file should also map port 80 on your computer. Here is what I mean:

Edit hosts file:
```
# /etc/hosts on your local machine
127.0.0.1	localhost mywordpress
```

Create docker-compose.yml:
```
version: "3"

services:
  mywordpress:
    image: "wordpress:5.7.2"
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_USER: "root"
    ports:
       - "80:80"
    depends_on:
      - "mysql"
  mysql:
    image: "mariadb:10.2"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "wordpress"
      MYSQL_ROOT_PASSWORD: ""
  node:
     image: "node:14"
```

1. `docker-compose up -d`
2. Install WordPress at http://mywordpress/

```sh
$ docker-compose exec node bash
Creating wp-docker_node_run ... done
root@ed3ad390147c:/# curl -I http://mywordpress/  
HTTP/1.1 200 OK
Date: Mon, 19 Jul 2021 14:26:55 GMT
Server: Apache/2.4.38 (Debian)
X-Powered-By: PHP/7.4.21
Link: <http://mywordpress/index.php?rest_route=/>; rel="https://api.w.org/"
Content-Type: text/html; charset=UTF-8
```

Hope this helps! I'm going to close this issue since it is not an issue with WPGraphQL. :)
