### ISSUE TITLE
Add PHPStan to Travis CI

### ISSUE THREAD

**Issue by szepeviktor** [wp-graphql/wp-graphql#940]
While starting [static analysis](https://packagist.org/packages/szepeviktor/phpstan-wordpress) of this plugin I've found
`use WPGraphQL\Type\RootQueryType;` in Types.php.

Could you point out where `RootQueryType` class gets defined?

Thank you.

**Comment by szepeviktor** [comment]
`TypeRegistry::prepare_type` only instantiates a `new WPObjectType`

**Comment by jasonbahl** [comment]
Ah! Looks like this might be some leftover `use` statements from a refactor. I'll look into it, but I think we can remove the `use` statements here: https://github.com/wp-graphql/wp-graphql/blob/develop/src/Types.php#L8-L13

**Comment by szepeviktor** [comment]
@jasonbahl Please consider using @phpstan , it has great benefits.

`phpstan.neon.dist`

```yaml
#$ composer require --dev phpstan/phpstan-shim szepeviktor/phpstan-wordpress
#$ vendor/bin/phpstan analyze

includes:
    - phar://phpstan.phar/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
# TODO    level: max
    level: 0
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - %currentWorkingDirectory%/src/
    autoload_files:
        - %currentWorkingDirectory%/wp-graphql.php
    ignoreErrors:
        # Uses func_get_args()
        - '#^Function apply_filters invoked with ([3456789]|10) parameters, 2 required\.$#'
        - '#^Function do_action invoked with [3456789] parameters, 1-2 required\.$#'
        - '#^Function current_user_can invoked with 2 parameters, 1 required\.$#'
```
